# version 3 of docker compose is loaded with more features.

# docker version 3 have some features related to docker swarm and docker stack.

version: '3'
services:
  redis:
    image: redis

  db:
    image: postgres

  vote_app:
    build: ./vote
    ports:
      - 6001:80
    depends_on:
      - redis

  result:
    build: ./result
    ports:
      - 6000:80

  worker:
    build: ./worker
